Git COMMANDALARI:
    - GCNotificationStatus BRANCH QAYSI BRANCHDA TURGANIMIZNI ANIQLAYDI
    - GIT CHECKOUT -B <NEW BRANCH NAME> YANGI BRANCH YARATADI VA SHU BRANCHGA O'TADI
    - GIT CHECKOUT -B <EXITION BRANCH NAME> OLDINDAN MAVJUD BRANCH NOMI KO'RSATILSA SHU BRANCHGA O'TADI
    - GIT PUSH ORIGIN HEAD - YANGI YARATILGAN BRANCHDAN TURIB MAIN BRANCHGA PULL REQUEST QILADI
    - GIT CLONE <REPOSITORIY LINK> REPOSITORIYNI  KOMPYUTERGA CLONE QILIB OLADI

GITHUB BILAN ISHLASH:
    - GITHUBDA FORK QILISH - GITHUBDA BIROR REPOSITORIYNI NUSXASINI O'ZIMIZNING GITHUB ACCOUNTDA YARATIB BERADI
